Fix logic issue with garage door.
jesserockz/athom-configs pull request #10
Opened 2022-07-28 03:37 UTC by gwaland

In home assistant if the garage door is closed and you call cover.close on the entity it will open the garage.  The expected functionality is that nothing will happen as the garage is already closed. 

In home assistant if the garage door is open and you call cover.open on the entity it will close the garage.  The expected functionality is that nothing will happen as the garage is already open. 

This pull request adds a check in each command to make this function as expected.

2022-07-28 04:40 UTC, jesserockz requested changes

2022-07-28 04:40 UTC, jesserockz commented on athom-garage-door.yaml
> +              lambda: 'return id(contact).state == false;'
```suggestion
              lambda: 'return !id(contact).state;'
```

2022-07-28 04:40 UTC, jesserockz commented on athom-garage-door.yaml
> +              lambda: 'return id(contact).state == true;'
```suggestion
              lambda: 'return id(contact).state;'
```

2022-07-28 14:00 UTC, gwaland commented on athom-garage-door.yaml
> +              lambda: 'return id(contact).state == false;'
Adjustments added

2022-08-02 00:32 UTC, gwaland commented
I'm confused about the ci build fail on this?  I didn't submit this 35 days ago.

2022-12-22 23:49 UTC, merged